### PR TITLE
Enable/Disable EAS accord. to profiles

### PR DESCRIPTION
**Pull request by iamlooper**
Docs: https://www.kernel.org/doc/html/v5.9/admin-guide/sysctl/kernel.html#sched-energy-aware and https://source.android.com/devices/tech/perf/boot-times

### CODE REVIEW

**Comment by NotZeetaa** [comment]
U are chaging 2 other things
Don't change

**Comment by ImSpiDy** [comment]
@NotZeetaa 69 changes on a commit

**Comment by iamlooper** [comment]
> U are chaging 2 other things Don't change

Bruh WTF

**Comment by iamlooper** [comment]
> U are chaging 2 other things Don't change

I am pretty sure that you don't want my commit to be accepted

**Comment by iamlooper** [comment]
> U are chaging 2 other things Don't change

See the docs. I have added it also because of reason

**Comment by NotZeetaa** [comment]
> > U are chaging 2 other things Don't change
> 
> I am pretty sure that you don't want my commit to be accepted

Its not that, u are changing something which doesn't makes sense for the commit message

**Comment by ImSpiDy** [comment]
@iamlooper Ok sar u are pro God I don't know anything

**Comment by iamlooper** [comment]
> > > U are chaging 2 other things Don't change
> > 
> > 
> > I am pretty sure that you don't want my commit to be accepted
> 
> Its not that, u are changing something which doesn't makes sense for the commit message

TF. Ok, I will send only EAS node pr

**Comment by iamlooper** [comment]
> @iamlooper Ok sar u are pro God I don't know anything

-_-

**Comment by shubhamxdd** [comment]
@NotZeetaa

**Pull request closed without merging**
